import { describe, expect, it } from 'vitest'
import { renderAgentPreset, agentConfigHash } from '../materialize.ts'
import type { AgentConfig } from '../../types.ts'

const agent: AgentConfig = {
  id: 'referee',
  persona: 'You are the referee.\nLine two.',
  model: { provider: 'deepseek-official', model: 'deepseek-v4-flash' },
  memory: 'none',
  tools: ['bash', 'read'],
  promptSections: [{ name: 'guide', order: 100, text: 'Follow the guide.' }],
}

describe('renderAgentPreset', () => {
  it('emits a reference snapshot with config-hash header and persona row', () => {
    const out = renderAgentPreset(agent, 'hash123', '0.0.15')
    expect(out).toContain('generated by @deepseek-ai/dsh-workflow-engine v0.0.15')
    expect(out).toContain('config-hash hash123')
    expect(out).toContain('NOT a standalone runnable preset')
    expect(out).toContain("  name: '@deepseek-ai/dsh-persona'")
    expect(out).toContain('You are the referee.')
    expect(out).toContain('# tools (reference only')
  })

  it('annotates prompt sections as reference comments', () => {
    const out = renderAgentPreset(agent, 'h', '0.0.15')
    expect(out).toContain('# prompt sections (reference only)')
    expect(out).toContain('guide')
  })
})

describe('agentConfigHash', () => {
  it('is stable and sensitive to config changes', () => {
    expect(agentConfigHash(agent)).toBe(agentConfigHash(agent))
    expect(agentConfigHash(agent)).not.toBe(agentConfigHash({ ...agent, persona: 'different' }))
  })
})
