/**
 * Materialization: regenerate a per-flow `agent.cordis.yml` reference
 * snapshot for each agent on every run — atomic write, skip when unchanged
 * (G8/G9). Pure write-only; not consumed by the preset roster.
 * @module @deepseek-ai/dsh-workflow-engine/materialize
 */

import { createHash } from 'node:crypto'
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { AgentConfig } from '../types.ts'

export interface MaterializeOptions {
  workspaceRoot: string
  flowId: string
  pluginVersion: string
}

/** Render an agent.cordis.yml reference snapshot for one agent. */
export function renderAgentPreset(agent: AgentConfig, configHash: string, version: string): string {
  const lines: string[] = []
  lines.push(`# generated by @deepseek-ai/dsh-workflow-engine v${version} / config-hash ${configHash}`)
  lines.push('# Configuration reference snapshot — NOT a standalone runnable preset.')
  lines.push('# Model route, memory mode, and tool selection are engine-owned and omitted.')
  lines.push(`# agent id: ${agent.id}`)
  lines.push('')
  lines.push('- id: persona')
  lines.push("  name: '@deepseek-ai/dsh-persona'")
  lines.push('  config:')
  lines.push('    text: |-')
  for (const line of agent.persona.split('\n')) lines.push(`      ${line}`)
  if (agent.promptSections && agent.promptSections.length > 0) {
    lines.push('')
    lines.push('# prompt sections (reference only)')
    for (const s of agent.promptSections) {
      lines.push(`# - section ${s.name} (order ${s.order}):`)
      for (const line of s.text.split('\n')) lines.push(`#     ${line}`)
    }
  }
  if (agent.tools && agent.tools.length > 0) {
    lines.push('')
    lines.push(`# tools (reference only, platform-branching unknown): ${agent.tools.join(', ')}`)
  }
  lines.push('')
  return lines.join('\n')
}

export function agentConfigHash(agent: AgentConfig): string {
  return createHash('sha256').update(JSON.stringify(agent)).digest('hex').slice(0, 16)
}

/** Materialize all agents under `<workspace>/<flowId>/agent/<agentId>/`. */
export async function materializeAgents(
  agents: Record<string, AgentConfig>,
  opts: MaterializeOptions,
): Promise<string[]> {
  const written: string[] = []
  for (const agent of Object.values(agents)) {
    const dir = join(opts.workspaceRoot, opts.flowId, 'agent', agent.id)
    const file = join(dir, 'agent.cordis.yml')
    const content = renderAgentPreset(agent, agentConfigHash(agent), opts.pluginVersion)
    await mkdir(dir, { recursive: true })
    let same = false
    try {
      const existing = await readFile(file, 'utf8')
      same = existing === content
    } catch { /* missing or unreadable */ }
    if (same) continue
    const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
    await writeFile(tmp, content, 'utf8')
    await rename(tmp, file)
    written.push(file)
  }
  return written
}
